name: "Druid Build"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        druid-version: [
          0.23.0,
          0.22.1, 0.22.0,
          0.21.1, 0.21.0,
          0.20.2, 0.20.1, 0.20.0,
          0.19.0, 0.18.1, 0.18.0, 0.17.1, 0.17.0
        ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            DRUID_VERSION=${{ matrix.druid-version }}
          push: false
      -
        name: Test
        run: mvn clean verify
