# Builds and pushes Hadoop image to Docker Hub

name: "Hadoop CI"

on:
  push:
    branches:
      - "hadoop"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hadoop-version: [
          2.2.0,
          2.3.0,
          2.4.0, 2.4.1,
          2.5.0, 2.5.1, 2.5.2,
          2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5,
          2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7,
          2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5,
          2.9.0, 2.9.1, 2.9.2,
          2.10.0, 2.10.1, 2.10.2,
          3.0.0-alpha1, 3.0.0-alpha2, 3.0.0-alpha3, 3.0.0-alpha4, 3.0.0-beta1,
          3.0.0, 3.0.1, 3.0.2, 3.0.3,
          3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4,
          3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4,
          3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4
        ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            HADOOP_VERSION=${{ matrix.hadoop-version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hadoop:${{ matrix.hadoop-version }}
